set -g prefix C-z
set -g default-terminal 'tmux-256color'
set -g aggressive-resize on
set -sg escape-time 0
set -g base-index 1
set -g mouse on
set -g bell-action none
setw -g pane-base-index 1
set -s extended-keys on
set -s terminal-features 'xterm*:clipboard:ccolour:cstyle:focus:title,screen*:title,rxvt*:ignorefkeys,xterm*:extkeys'
