#!/usr/bin/bash

LOOPBACK="cava_loopback"
HDMI="alsa_output.pci-0000_00_1f.3.hdmi-stereo"
BLUETOOTH="bluez_output.F8_4E_17_E1_AC_41.a2dp-sink"
SONOS=$(findsonos)

SINKS=( "$LOOPBACK" "$HDMI" "$SONOS" "$BLUETOOTH" )
AVAILABLE_SINKS=()

while read -r stream; do
  sink=$(echo "$stream" | awk '{print $22}')
  for s in "${SINKS[@]}"; do
    if [ "$sink" == "$s" ]; then
      AVAILABLE_SINKS+=("$sink")
    fi
  done
done < <(pactl list sinks short)

LIST=$(echo "${AVAILABLE_SINKS[@]}" | tr ' ' ',')

pactl load-module module-combine-sink sink_name=cava_sink \
  sink_properties=device.description=CavaSink \
  slaves="$LIST"
