#!/usr/bin/bash

DISPLAY=$(hyprctl monitors -j | jq -r '.[] | select (.focused).name' )

wf-recorder -a -o "$DISPLAY" -f "$HOME/Videos/Screencasts/Screen-recording-$(date -Isecond | cut -d'+' -f1).mp4"
