#!/usr/bin/python3

import os
import sys
import time


def write_output(output):
    sys.stdout.write(output + '\n')
    sys.stdout.flush()


def get_stats(path="/"):
    stats = os.statvfs('/')
    free = round(stats.f_bavail * 100 / stats.f_blocks, 0)
    used = round((stats.f_blocks - stats.f_bfree) * 100 / stats.f_blocks, 0)
    return int(free), int(used)


def main(state):
    if sys.argv[1] == 'expanded':
        write_output(f"{free}%")
        return
    write_output('')


if __name__ == '__main__':
    free, used = get_stats()
    main(sys.argv[1])
