#!/usr/bin/python3
import os
import sys
import subprocess
import time

COOLDOWN = 0.2
LOCK = "/tmp/expand_toolbar.lock"
SCRIPTS = "/home/kingsley/.config/waybar/custom_modules"


if __name__ == '__main__':
    executable = os.path.join(SCRIPTS, sys.argv[1])
    while True:
        if os.path.exists(LOCK):
            subprocess.call([executable, "expanded"])
        else:
            subprocess.call([executable, "collapsed"])
        time.sleep(COOLDOWN)
