#!/usr/bin/python3
import sys


def write_output(output):
    sys.stdout.write(output + '\n')
    sys.stdout.flush()


def main(state):
    if state == 'expanded':
        write_output(' ')
        return
    write_output(' ')


if __name__ == "__main__":
    main(sys.argv[1])
