source-file ~/.config/tmux/plugins.tmux.conf
source-file ~/.config/tmux/keybindings.tmux.conf
source-file ~/.config/tmux/colors.tmux.conf
source-file ~/.config/tmux/appearance.tmux.conf
source-file ~/.config/tmux/base.tmux.conf

run '~/.tmux/plugins/tpm/tpm'
