bind x kill-pane
bind k kill-window
bind ! kill-session
bind q send-keys C-a x Enter
bind r source-file ~/.config/tmux/tmux.conf
bind t select-layout tiled

# Set new panes to open in current directory
bind c new-window -c '#{pane_current_path}'
bind '"' split-window -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# smart pane switching with awareness of vim splits
set -g @vim_navigator_mapping_left "C-S-h"
set -g @vim_navigator_mapping_down "C-S-j"
set -g @vim_navigator_mapping_up "C-S-k"
set -g @vim_navigator_mapping_right "C-S-l"
set -g @vim_navigator_mapping_prev ""
