start-at-login = true
after-startup-command = [
  'exec-and-forget open -a /Applications/Arc.app',
  'exec-and-forget open -a /Applications/Ghostty.app',
  'exec-and-forget open -a /Applications/Slack.app',
  'exec-and-forget open -a /Applications/Mail.app',
  'exec-and-forget sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = [
  '/bin/bash', '-c', 'sketchybar --trigger aerospace_workspace_change',
]

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[gaps]
inner.vertical =   20
inner.horizontal = 20
outer.top =        50
outer.right =      10
outer.bottom =     10
outer.left =       10

# Window rules
[[on-window-detected]]
if.app-name-regex-substring = 'OpenVPN Connect'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'WhatsApp'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'qemu-system-aarch64'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Preview'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Arc'
if.during-aerospace-startup = true
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'Ghostty'
if.during-aerospace-startup = true
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'Obsidian'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 3']

[[on-window-detected]]
if.app-name-regex-substring = 'Slack'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-name-regex-substring = 'Mail'
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 5']

[[on-window-detected]]
if.app-name-regex-substring = '1Password'
if.during-aerospace-startup = true
check-further-callbacks = true
run = ['layout tiling', 'move-node-to-workspace 9']

# Keybindings
[mode.main.binding]
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Fullscreen
alt-f = 'fullscreen'
alt-shift-f = 'fullscreen'

# Resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Move workspaces
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Switch between workspaces
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# User apps
alt-enter = 'exec-and-forget open -a /Applications/Ghostty.app'
alt-n = 'exec-and-forget open -a /Applications/Obsidian.app'
alt-s = 'exec-and-forget open -a /Applications/Slack.app'

# System apps
alt-b = 'exec-and-forget open -a /System/Library/CoreServices/Finder.app'
alt-m = 'exec-and-forget open -a /System/Applications/MissionFinder\ Control.app'

# modes
alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
