preload = ~/.cache/wallpapers/fabian-irsara.jpg

wallpaper = eDP-1,~/.cache/wallpapers/fabian-irsara.jpg
wallpaper = DP-1,~/.cache/wallpapers/fabian-irsara.jpg
wallpaper = DP-2,~/.cache/wallpapers/fabian-irsara.jpg
wallpaper = DP-3,~/.cache/wallpapers/fabian-irsara.jpg
