# mod key
$mod = ALT

# so aquamarine can detect the external display
env = LIBSEAT_BACKEND, logind
env = AQ_DRM_DEVICES, /dev/dri/card1
env = AQ_NO_MODIFIERS, 1

# clipboard
exec-once = wl-paste --watch cliphist store

# environment variables
env = PATH, $PATH:$HOME/.local/bin
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# compositor level stuff
exec-once = hyprpaper &
exec-once = hypridle &
exec-once = gnome-keyring &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
