# TODO: maybe split this all out
windowrulev2=float,title:^(Open Files)$
windowrulev2=size 1200 800,title:^(Open Files)$
windowrulev2=center,floating:1,title:^(Open Files)$

windowrulev2=float,title:^(Save File)$
windowrulev2=size 1200 800,title:^(Save File)$
windowrulev2=center,floating:1,title:^(Save File)$

windowrulev2=float,class:^(pavucontrol)$
windowrulev2=size 1200 800,class:^(pavucontrol)$
windowrulev2=center,floating:1,class:^(pavucontrol)$

windowrulev2=float,title:^(Bluetooth Devices)$
windowrulev2=size 1200 800,title:^(Bluetooth Devices)$
windowrulev2=center,floating:1,title:^(Bluetooth Devices)$

windowrulev2=float,class:^(1Password)$
windowrulev2=size 1200 800,class:^(1Password)$
windowrulev2=center,floating:1,class:^(1Password)$

# this is annoying, just hide it
windowrulev2=float,title:^(meet.google.com is sharing (a window|your screen).)$
windowrulev2=size 0 0,title:^(meet.google.com is sharing (a window|your screen).)$

# layer rules
layerrule = blur, gtk-layer-shell
layerrule = ignorezero, gtk-layer-shell
layerrule = blur, waybar
layerrule = ignorezero, waybar

# workspace placements
windowrulev2=workspace 1 silent,class:^(zen)$
windowrulev2=workspace 3 silent,class:^(obsidian)$
windowrulev2=workspace 4 silent,class:^(Slack)$
windowrulev2=workspace 7 silent,class:^(Spotify)$

# application stuff
exec-once = flatpak run com.slack.Slack
exec-once = flatpak run com.spotify.Client
exec-once = flatpak run app.zen_browser.zen
exec-once = ghostty
