windowrule {
  name = floating-files
  match:title = ^(Open Files)$
  float = on
  center = on
  size = 1200 800
}

windowrule {
  name = save-files-dialog
  match:title = ^(Save File)$
  float = on
  center = on
  size = 1200 800
}

windowrule {
  name = pavucontrol
  match:class = ^(pavucontrol)$
  float = on
  center = on
  size = 1200 800
}

windowrule {
  name = bluetooth-devices
  match:class = ^(Bluetooth Devices)$
  float = on
  center = on
  size = 1200 800
}

windowrule {
  name = 1password
  match:class = ^(1Password)$
  float = on
  center = on
  size = 1200 800
}

windowrule {
  name = meet-indicator
  match:title = ^(meet.google.com is sharing (a window|your screen).)$
  float = on
  size = 0 0
}

# layer rules
layerrule = blur on, match:namespace gtk-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar

# workspace placements
windowrule=workspace 1 silent,match:class = ^(zen)$
windowrule=workspace 3 silent,match:class = ^(obsidian)$
windowrule=workspace 4 silent,match:class = ^(Slack)$
windowrule=workspace 7 silent,match:class = ^(Spotify)$

# application stuff
exec-once = flatpak run com.slack.Slack
exec-once = flatpak run com.spotify.Client
exec-once = flatpak run app.zen_browser.zen
exec-once = ghostty
