# mod key
$mod = ALT

# cursors on mirrored displays
env = WLR_NO_HARDWARE_CURSORS,1

# clipboard
exec-once = wl-paste --watch cliphist store

# environment variables
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# compositor level stuff
exec-once = hyprpaper &
exec-once = hypridle &
exec-once = gnome-keyring &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
