binds {
  workspace_back_and_forth = true
  allow_workspace_cycles = true
}

# Utility keymaps
bind = $mod, RETURN, exec, ghostty
bind = $mod, Q, killactive,
bind = $mod, M, exit,
bind = $mod, B, exec, nautilus
bind = $mod, F, fullscreen
bind = $mod SHIFT, F, fullscreen, 1
bind = $mod, C, centerwindow,
bind = $mod, D, exec, ags toggle "launcher"
bind = MOD3, SPACE, exec, ags toggle "launcher"
bind = $mod, S, togglesplit,
bind = $mod, Escape, exec, ags toggle "powermenu"
bind = $mod, r, exec, ags quit; ~/.config/ags/build; gjs -m ~/bin/widgets
bind = $mod, i, exec, ags inspect --instance astal

# Move focus with mod + vim keys
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

# Switch workspaces with mod + [0-9]
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10
bind = $mod, TAB, workspace, previous

# Move active window to a workspace with mod + SHIFT + [0-9]
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mod + scroll
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# Move/resize windows with mod + LMB/RMB and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# media & volume
bind = , XF86AudioLowerVolume, exec, "$HOME/bin/volume" --down # rotary encoder
bind = , XF86AudioRaiseVolume, exec, "$HOME/bin/volume" --up # rotary encoder
bind = , XF86AudioMute, exec, playerctl --player="spotify,any" play-pause #rotary encoder
bind = , code:67, exec, "$HOME/bin/volume" --mute #f1
bind = , code:68, exec, "$HOME/bin/volume" --down #f2
bind = , code:69, exec, "$HOME/bin/volume" --up #f3

# display
bind = , code:71, exec, brightnessctl set 5%- #f5
bind = , code:72, exec, brightnessctl set +5% #f6

# screencapture
bind = MOD3, 3, exec, ags request output
bind = MOD3, 4, exec, ags toggle "screencapture"
