# top of the config file
# just mirror all other displays.
monitor = FALLBACK,preferred,auto,1,bitdepth,8
monitor = eDP-1,preferred,auto,1,bitdepth,8
monitor = HDMI-A-1,preferred,auto,1,bitdepth,8

# run swayidle and suspend monitors if in swaylock
# exec-once = "${HOME}/.config/hypr/scripts/display/idle"
exec-once = hypridle

# clamshell mode stuff
bindl=,switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1,disable"
bindl=,switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1,preferred,auto,1,bitdepth,8"
