#!/usr/bin/bash

# get the sinks
SINKS="$(pactl list sinks)"
HDMI="alsa_output.pci-0000_00_1f.3.hdmi-stereo"
BLUETOOTH="bluez_output.F8_4E_17_E1_AC_41.a2dp-sink"
SONOS=$(paste -d\| \
<(printf '%s' "$SINKS" | grep 'node.name' | cut -d'"' -f 2) \
<(printf '%s' "$SINKS" | grep 'device.description' | rev | cut -d'"' -f 2 | rev) \
| grep 'Bedroom' | head -1 | cut -d'|' -f 1)

# set various variables
OUTPUT="$HDMI" # default
CURRENT=$(pactl list short sinks | grep RUNNING | awk '{print $2}' | head -1)
BLUETOOTH_CONNECTED=$(pactl list short sinks | grep -c "$BLUETOOTH")

# toggle between HDMI and Sonos
if [ "$OUTPUT" == "$CURRENT" ]; then
  OUTPUT="$SONOS"
fi

# But if bluetooth is connected, use it
if [ "$BLUETOOTH_CONNECTED" -gt 0 ]; then
  OUTPUT="$BLUETOOTH"
fi


while read -r stream; do
  idx=$(echo "$stream" | awk '{print $1}')
  pactl set-default-sink "$OUTPUT"
  pactl move-sink-input "$idx" "$OUTPUT"
done < <(pactl list sink-inputs short)
