#!/usr/bin/bash

DISPLAY="DP-[0-9]"
DISPLAY_ACTIVE=$(hyprctl monitors | grep -c -w "$DISPLAY")

if [ "$DISPLAY_ACTIVE" -eq 0 ]; then
  # we don't want to disable the laptop display
  # if an external display is not active
  exit 0
fi

LAPTOP="eDP-1"
STATE=$(cat /proc/acpi/button/lid/LID/state | grep open -c)

if [ "$STATE" -eq 1 ]; then
    hyprctl keyword monitor "$LAPTOP,preferred,auto,1"
else
    hyprctl keyword monitor "$LAPTOP,disable"
fi
