#!/usr/bin/bash

VPN=$(nmcli con show --active | grep -c vpn)

if [ "$VPN" -eq 0 ]; then
    echo "Connecting to VPN..."
    otp | nmcli con up "Farnborough (FAB)" --ask > /dev/null
fi

echo "Logging in..."
op item get "Red Hat" --fields label="kerberos" | kinit gzuccare@IPA.REDHAT.COM > /dev/null
